# Generated by Django 4.1.7 on 2023-02-18 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Self-Contain', 'Self-Contain'), ('Flat', 'Flat'), ('Boys-Quater', 'Boys-Quater')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodge_name', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('subsequent_price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('balcony', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('kitchen', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('waldrop', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('tiled', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('distance_to_school', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_images')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.house')),
            ],
        ),
    ]
