# Generated by Django 4.1.7 on 2023-02-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_house_posted_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='house',
            name='type',
            field=models.CharField(blank=True, choices=[('Self-Contain', 'Self-Contain'), ('Flat', 'Flat'), ('Boys-Quater', 'Boys-Quater')], max_length=30, null=True),
        ),
    ]
