# Generated by Django 4.1.7 on 2023-02-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_delete_category_house_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='lodge_name',
            new_name='lodge_id',
        ),
    ]
