# Generated by Django 4.1.7 on 2023-02-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_house_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='available',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
    ]
